/**
 * Packs a built bundle into a self-extracting Home Assistant inline dashboard
 * resource.
 *
 * Inline resources are stored as a data: URI and cap at roughly 128 KB of
 * source, while the full ACD bundle is well past 200 KB. So the bundle travels
 * gzipped + base64 inside a tiny loader module that inflates it and imports it
 * from a blob URL. Cards register within a few milliseconds — comfortably
 * inside the window Lovelace waits for custom elements to appear.
 *
 * Usage:
 *   npm run build
 *   node scripts/pack-inline.mjs [dist/acd-cards.js] [dist/acd-cards.inline.js]
 *
 * Then paste the output file as the `content` of the inline resource
 * (Settings → Dashboards → Resources), or push it via the HA MCP tool
 * `ha_config_set_dashboard_resource`.
 *
 * The base64 payload is emitted as an array of short lines joined at runtime:
 * a single multi-megabyte line trips editors, diff tools and agent file
 * readers alike.
 */
import { gzipSync, constants } from "node:zlib";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const input = process.argv[2] ?? "dist/acd-cards.js";
const output = process.argv[3] ?? "dist/acd-cards.inline.js";
const LINE = 180;
const INLINE_LIMIT = 131072;

const source = readFileSync(input);
const gz = gzipSync(source, { level: constants.Z_BEST_COMPRESSION });
const b64 = gz.toString("base64");

const lines = [];
for (let i = 0; i < b64.length; i += LINE) {
  lines.push(`"${b64.slice(i, i + LINE)}"`);
}

const loader = `/* ACD Cards — self-extracting inline bundle
 * Generated by scripts/pack-inline.mjs — do not edit by hand.
 * Source: ${input} (${source.length} bytes, gzip ${gz.length} bytes)
 *
 * Home Assistant inline dashboard resources cap at ~128 KB of source, so the
 * bundle ships compressed and is inflated here, then imported as a module from
 * a blob URL.
 *
 * Requires DecompressionStream (Chrome 80+, Safari 16.4+, Firefox 113+).
 */
const B64 = [
${lines.join(",\n")}
].join("");
try {
  const bytes = Uint8Array.from(atob(B64), (c) => c.charCodeAt(0));
  const stream = new Blob([bytes])
    .stream()
    .pipeThrough(new DecompressionStream("gzip"));
  const code = await new Response(stream).text();
  const url = URL.createObjectURL(new Blob([code], { type: "text/javascript" }));
  await import(/* @vite-ignore */ url);
  URL.revokeObjectURL(url);
} catch (err) {
  console.error("[acd-cards] self-extracting bundle failed to load", err);
}
`;

mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, loader);

const pct = ((loader.length / INLINE_LIMIT) * 100).toFixed(0);
console.log(
  `${input} ${source.length} B → ${output} ${loader.length} B ` +
    `(${pct}% de la limite inline de ${INLINE_LIMIT} B, ` +
    `${loader.split("\n").length} lignes)`
);
if (loader.length > INLINE_LIMIT) {
  console.error("ATTENTION : au-delà de la limite inline, il faut découper.");
  process.exitCode = 1;
}
